name: CWYOD Backend Docker Image

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        registry: ttchatbaard.azurecr.io
        username: ttchatbaard
        password: LrsMQekaLkBxb0HpxrvVLtn+cSKQrOid00bd0us3Vw+ACRBXQecI
    
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run:
        docker pull ttchatbaard.azurecr.io/cwyod_backend:latest || true;
        docker build . --file extensions/docker/Backend.Dockerfile --cache-from ttchatbaard.azurecr.io/cwyod_backend:latest --tag ttchatbaard.azurecr.io/cwyod_backend:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER;
        docker tag ttchatbaard.azurecr.io/cwyod_backend:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER ttchatbaard.azurecr.io/cwyod_backend:latest;
        docker push ttchatbaard.azurecr.io/cwyod_backend:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER;
        docker push ttchatbaard.azurecr.io/cwyod_backend:latest;
        